server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        use_sql_comments: true
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  output:
    ansi:
      enabled: always

  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 2000
        one-indexed-parameters: on

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


